### ISSUE TITLE
[TODO] Finish BoM

### ISSUE THREAD

**Issue by fifteenhex** [breadbee/breadbee#11]

**Comment by kadamski** [comment]
The tvsarray is something like a SP3051 from little fuse ?

**Comment by fifteenhex** [comment]
I went for the cheapest parts I could get from taobao for everything. The part is a no-name generic thing but they list SRV05-4 which is an onsemi part. On a quick glance it looks identical to the SP3051.
On all the boards I've built so far I haven't mounted it.

**Comment by kadamski** [comment]
I guess b11b79b941a11807d1c2f3215691a770435c06a1 fixes that, right?
