### ISSUE TITLE
[QUESTION] 0xFD000000 address

### ISSUE THREAD

**Issue by kadamski** [breadbee/breadbee#18]
I've seen the 0xFDxxxxxx address prefix in some kernel code in places where I would expect the 0x1fxxxxxx. What is this address? Is this like a shadow copy of this area? Is MMU in the kernel configured to put the physical region there or something else?

**Comment by fifteenhex** [comment]
>Is MMU in the kernel configured to put the physical region there or something else?

It's this one. All access in the kernel has to go through a mapping and not directly.
In the vendor kernel they map the io space (0x1f000000 block) to 0xfd000000 so they can hardcode addresses in the drivers.
