### ISSUE TITLE
Powering the dascham + USB ethernet

### ISSUE THREAD

**Issue by mbilloo** [breadbee/breadbee#29]
@fifteenhex , my strategy for powering the dashcam and having USB (initially for Ethernet) was to use an external power supply instead of the battery and use a spliced micro USB cable that doesn't have power coming out to the USB ethernet adapter. That would be provided by another spliced cable. See attached diagram.
![dashcampower_and_usb](https://user-images.githubusercontent.com/6383052/83974270-38e2ea00-a8ba-11ea-8b21-976bd7034415.jpg)

Was that were you doing to test USB? I imagine the USB port on the dashcam is meant to power the dashcam and charge the battery (instead of providing power to an external device)

**Comment by fifteenhex** [comment]
![IMG_20200608_205449](https://user-images.githubusercontent.com/682372/84027814-8fd7e480-a9ca-11ea-83e3-42efa8466027.jpg)

This is how I've been doing it. I attached a cheap USB A breakout to the internal pads for the port and then use the supplied USB cable to power it. The supplied cable doesn't have data lines so it works perfectly for supplying 5v and not messing with the data lines.
