### ISSUE TITLE
Which kernel to use for development?

### ISSUE THREAD

**Issue by mbilloo** [breadbee/breadbee#36]
I'm resuming work on the MUSB controller driver targeting the m5 camera after a hiatus. Which kernel (and in turn, branch) should we use? IIRC from a previous post, you mentioned that a shell from an initramfs is your target for 5.8/5.9. Is that still the case? Would you like help testing the 5.8/5.9 for regressions?

**Comment by fifteenhex** [comment]
Sorry, for some reason I'm not getting notifications.

Please use https://github.com/fifteenhex/linux/tree/mstar_dev_v5_8_rebase_cleanup
