### ISSUE TITLE
Inductor values missing

### ISSUE THREAD

**Issue by kadamski** [breadbee/breadbee#8]
The inductor values on the schematic are missing. I suppose you have left them without values are you wanted to experiment with getting the voltage ripple. What did you end up choosing, 1.5uH ?

**Comment by fifteenhex** [comment]
The current schematic was from when I was still doing the bring up and filling in the values.

The inductors I'm using at the moment are 1.5uH. The specific part is sunlord SPH202012H1R5MT but there are a number of off-brand makers of similar parts.
